# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43cc9e72087b61c72649cbabcd052072"
name = "SkyNet Online Shipping"
application_url = "https://7dca-223-185-24-22.ngrok-free.app"
embedded = false
handle = "skypoint-shipping"

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "/api/shopify/customers/redact"
  customer_data_request_url = "/api/shopify/customers/data_request"
  shop_deletion_url = "/api/shopify/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/api/shopify/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/api/shopify/orders/updated"

  [[webhooks.subscriptions]]
  topics = [ "orders/cancelled" ]
  uri = "/api/shopify/orders/cancelled"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/shopify/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_products,write_products,read_shipping,write_shipping,read_fulfillments,write_fulfillments,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ 
  "https://7dca-223-185-24-22.ngrok-free.app/api/shopify/auth"
]
