# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "43cc9e72087b61c72649cbabcd052072"
name = "Skypoint Shipping"
application_url = "https://dev-skynet-online.azurewebsites.net"
embedded = false
handle = "skynet-pudo-shipping"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  uri = "/api/shopify/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/orders/updated"
  topics = [ "orders/updated" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_fulfillments,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_script_tags,read_shipping,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://dev-skynet-online.azurewebsites.net/api/shopify/auth"
]
